In [1]:
pip install torch torchvision torchaudio

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
import torch
x = torch.rand(3,5)
print(x)

tensor([[0.5367, 0.3270, 0.1402, 0.0904, 0.1403],
        [0.8983, 0.4773, 0.8297, 0.3019, 0.4264],
        [0.6908, 0.0366, 0.1419, 0.0252, 0.7350]])


In [ ]:
#check gpu availability
print(torch.cuda.is_available())
#PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
#DL framework , help to run code faster using gpus 

False


In [ ]:
 #tensor array of numbers which represents data


In [14]:
scalar = torch.Tensor(7)
print(scalar.ndim)
print(scalar.shape)

1
torch.Size([7])


In [12]:
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [18]:
matrix = torch.tensor([[7,8],
                     [4,6]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix[1])


tensor([[7, 8],
        [4, 6]])
2
torch.Size([2, 2])
tensor([4, 6])


In [24]:
m = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print(m.shape)
print(m.ndim)
print("trying different combinations ")
print(m[0,1,1])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
3
trying different combinations 
tensor(5)


In [ ]:
#random tensor
r = torch.rand(1,3,4)
print(r)

In [35]:
img = torch.rand(size=(3,244,244))
print(img)
print(img.shape)
print(img.ndim)
print(img[1,2,2])

tensor([[[2.6368e-01, 3.4439e-01, 2.5634e-01,  ..., 5.9213e-01,
          6.2377e-01, 5.5124e-01],
         [5.2513e-01, 4.6652e-01, 4.1178e-02,  ..., 3.2943e-01,
          6.2505e-03, 8.4018e-01],
         [1.7166e-01, 4.6423e-01, 1.1011e-01,  ..., 4.1075e-01,
          7.8770e-01, 3.5619e-01],
         ...,
         [3.0107e-01, 4.1206e-01, 2.5907e-01,  ..., 5.0657e-01,
          1.4321e-01, 9.2575e-01],
         [2.4978e-01, 9.4226e-01, 6.1109e-01,  ..., 3.2590e-01,
          2.0269e-01, 5.5346e-01],
         [8.9187e-01, 7.2272e-01, 3.0036e-01,  ..., 6.6440e-01,
          8.2392e-01, 2.2167e-01]],

        [[8.0869e-01, 8.9221e-01, 7.4185e-01,  ..., 1.8768e-01,
          4.3045e-01, 3.2924e-01],
         [5.5449e-01, 9.2544e-01, 8.7458e-01,  ..., 7.0273e-01,
          6.9369e-01, 8.7453e-01],
         [5.7842e-01, 4.3991e-01, 4.8115e-01,  ..., 1.5831e-02,
          5.2508e-01, 7.5933e-01],
         ...,
         [5.4826e-01, 5.5923e-01, 4.4275e-01,  ..., 5.0409e-01,
          3.870

In [40]:
#zeros and ones tensor
zeros = torch.zeros(size=(3,3))
print(zeros)
print(zeros.dtype)
ones = torch.ones(size=(3,3))
print(ones)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#creating a range