In [1]:
pip install torch torchvision torchaudio

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
import torch
x = torch.rand(3,5)
print(x)

tensor([[0.5629, 0.8027, 0.7972, 0.7440, 0.1069],
        [0.4713, 0.1296, 0.3668, 0.6467, 0.8936],
        [0.3450, 0.4716, 0.3866, 0.7962, 0.4867]])


In [ ]:
#check gpu availability
print(torch.cuda.is_available())
#PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
#DL framework , help to run code faster using gpus 

False


In [7]:
 #tensor array of numbers which represents data in range
one_to_ten = torch.arange(start=1,end=10,step=1)
print(one_to_ten)
print(torch.zeros_like(one_to_ten))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])


In [8]:
print('issue with git push')

issue with git push


In [9]:
scalar = torch.Tensor(7)
print(scalar.ndim)
print(scalar.shape)

1
torch.Size([7])


In [10]:
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [11]:
matrix = torch.tensor([[7,8],
                     [4,6]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix[1])


tensor([[7, 8],
        [4, 6]])
2
torch.Size([2, 2])
tensor([4, 6])


In [12]:
m = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print(m.shape)
print(m.ndim)
print("trying different combinations ")
print(m[0,1,1])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
3
trying different combinations 
tensor(5)


In [13]:
#random tensor
r = torch.rand(1,3,4)
print(r)

tensor([[[0.8671, 0.9788, 0.3323, 0.2699],
         [0.0576, 0.5491, 0.8922, 0.5521],
         [0.4977, 0.9989, 0.8197, 0.2644]]])


In [14]:
img = torch.rand(size=(3,244,244))
print(img)
print(img.shape)
print(img.ndim)
print(img[1,2,2])

tensor([[[0.8273, 0.2176, 0.6781,  ..., 0.3763, 0.5278, 0.8221],
         [0.2485, 0.7334, 0.7902,  ..., 0.2757, 0.5687, 0.7957],
         [0.8519, 0.5695, 0.0254,  ..., 0.9659, 0.3879, 0.0579],
         ...,
         [0.9953, 0.5685, 0.1497,  ..., 0.2984, 0.3096, 0.6002],
         [0.3783, 0.8942, 0.4477,  ..., 0.3407, 0.1655, 0.0536],
         [0.6057, 0.0886, 0.9439,  ..., 0.0543, 0.2557, 0.7070]],

        [[0.0156, 0.2206, 0.9881,  ..., 0.5597, 0.0917, 0.0086],
         [0.8281, 0.8685, 0.2302,  ..., 0.8320, 0.2437, 0.9868],
         [0.2212, 0.3097, 0.1186,  ..., 0.2607, 0.0335, 0.1923],
         ...,
         [0.7128, 0.5784, 0.8537,  ..., 0.4339, 0.2773, 0.6606],
         [0.1868, 0.4252, 0.8710,  ..., 0.6760, 0.6197, 0.8074],
         [0.3874, 0.8357, 0.1369,  ..., 0.6350, 0.4440, 0.2998]],

        [[0.7696, 0.5155, 0.7240,  ..., 0.9274, 0.2003, 0.9681],
         [0.1030, 0.7188, 0.9261,  ..., 0.1140, 0.6722, 0.4024],
         [0.3542, 0.9948, 0.6483,  ..., 0.6332, 0.5991, 0.

In [15]:
#zeros and ones tensor
zeros = torch.zeros(size=(3,3))
print(zeros)
print(zeros.dtype)
ones = torch.ones(size=(3,3))
print(ones)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [19]:
#torch dtypes
float32 = torch.tensor([3.0,6.0,9.0 ],
                       dtype=None,
                       device='cpu',
                       requires_grad=False)
print(float32)
#3 common erros whie dealing with dtypoes in torch
#1. tensor not right dtype
#2. tensor not right shape
#3. tensor not on right device

tensor([3., 6., 9.])
